// Emits server/utils/emails/logo.ts from the rendered icon-192.png bytes so
// transactional emails can embed the logo as an inline CID attachment instead
// of fetching it over HTTP (VKB-69: remote fetches break whenever the sending
// env's assets are protected or the public host runs an older release that
// does not ship the file yet). Kept next to generate-icons.js so a rebrand
// regenerates the email logo together with the icon set.

import { resolve } from 'node:path';

export const EMAIL_LOGO_MODULE_PATH = resolve(
  import.meta.dirname,
  '../../server/utils/emails/logo.ts',
);

const CHUNK_LENGTH = 72;

export const emailLogoModuleSource = (png) => {
  const base64 = png.toString('base64');
  const chunks = [];
  for (let i = 0; i < base64.length; i += CHUNK_LENGTH) {
    chunks.push(`  '${base64.slice(i, i + CHUNK_LENGTH)}',`);
  }
  return [
    '// Generated by scripts/generate-icons.js (bun run icons:gen) from the',
    '// rendered icon-192.png — do not edit by hand. The logo ships inside the',
    '// message as a CID attachment so mail clients never fetch it over HTTP',
    '// (VKB-69: remote logo fetches broke on protected/stale origins).',
    "export const EMAIL_LOGO_CONTENT_ID = 'vocabu-logo';",
    '',
    "export const EMAIL_LOGO_FILENAME = 'vocabu-logo.png';",
    '',
    'const BASE64_CHUNKS = [',
    ...chunks,
    '];',
    '',
    "export const EMAIL_LOGO_BASE64 = BASE64_CHUNKS.join('');",
    '',
  ].join('\n');
};
